version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: daily
    commit-message:
      prefix: deps
    groups:
      minor-versions:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: daily
    commit-message:
      prefix: deps
    groups:
      minor-versions:
        update-types:
          - "minor"
          - "patch"
