version: "2"

run:
  timeout: 10m
  tests: false
  allow-parallel-runners: true
  allow-serial-runners: true

linters:
  disable:
    - ineffassign
    - unused
  exclusions:
    rules:
      - text: "SA5008:" # duplicate struct tag "choice"
        linters:
          - staticcheck
