# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: traefik-forward-auth

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: binary

kos:
  - repository: "{{ .Env.REPOSITORY_NAME }}"
    tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
