# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: traefik-forward-auth

version: 2

builds:
  - main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary

kos:
  - tags:
      - "{{.Version}}"
      - latest
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64
